# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "cargo"
    directory: "/mirrord-protocol"
    schedule:
      interval: "daily"