[build.env]
passthrough = [
    "MIRRORD_LAYER_FILE",
]
# Dockerfile used for building mirrord-layer for x64 with very old libc
# this to support centos7 or Amazon Linux 2.
[target.x86_64-unknown-linux-gnu]
image ="ghcr.io/metalbear-co/ci-layer-build:latest"